name             'imawebui-docker'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures imawebui in docker'
long_description 'Installs/Configures imawebui in docker'
version          '0.1.0'
depends          'docker','0.36.0'
