name             'imaserver-rpm'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures imaserver-rpm'
long_description 'Installs/Configures imaserver-rpm'
version          '0.1.0'
