name             'svtperf-betademo'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures svtperf-betademo'
long_description 'Installs/Configures svtperf-betademo'
version          '0.1.0'
depends	         'imaserver'
